[package]
name = "timer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.83"
tokio = { version = "1.21.2", features = ["full"] }
futures = "0.3.25"
